import { Geist, Geist_Mono, Montserrat, Truculenta } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import { AppContextProvider } from "@/context/AppContext.js";

const montserrat = Montserrat({
  variable:"--font-montserrat",
  subsets:["latin"],
  weight:["400","500","600","700","800"]
})

const trucu = Truculenta({
  variable:"--font-truculenta",
  subsets:["latin"],
  weight:["400","600","800"],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${trucu.variable} antialiased`}
      >
        <AppContextProvider>
        <NavBar/>
        {children}
        <Footer/>
        </AppContextProvider>
      </body>
    </html>
  );
}
